services:
  postgresql-b:
    image: postgres:15-alpine
    container_name: postgresql-b
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgbackups:/backups
    ports:
      - "5432:5432"
    networks:
      - pg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    environment:
      DB_HOST_1: postgresql-b
      DB_PORT: 5432
      DB_NAME: books_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./app:/app
    networks:
      - pg-network
    depends_on:
      postgresql-b:
        condition: service_healthy

networks:
  pg-network:
    driver: bridge

volumes:
  pgdata:
  pgbackups: